### ISSUE TITLE
The mod is conflict with OptiFabric

### ISSUE THREAD

**Issue by italycalibur2019** [DawnTeamMC/Culinaire#11]
This is my error report：

**[20:06:25] [main/FATAL]: Mixin apply failed optifabric.compat.dawn.mixins.json:ItemRendererMixin -> net.minecraft.class_918: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.dawn.mixins.json:ItemRendererMixin]
org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.dawn.mixins.json:ItemRendererMixin]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:353) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_261]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_261]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) [?:1.8.0_261]
	at java.lang.Class.getDeclaredFields(Class.java:1916) [?:1.8.0_261]
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) [Optifine-mapped.jar:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:501) [Optifine-mapped.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at net.minecraft.class_128.method_559(class_128.java:101) [intermediary-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at net.minecraft.class_128.<init>(class_128.java:54) [intermediary-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:501)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:425)
	at net.minecraft.client.main.Main.main(Main.java:135)
	... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.dawn.mixins.json:ItemRendererMixin] from phase [DEFAULT] in config [optifabric.compat.dawn.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 22 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinApplicatorException: Unexpecteded IllegalArgumentException whilst applying the mixin class: [PreApply Phase -> optifabric.compat.dawn.mixins.json:ItemRendererMixin]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:353)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 22 more
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class com/hugman/dawn/mod/mixin/ItemRendererMixin targetting net.minecraft.class_918
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:93)
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:43)
	at me.modmuss50.optifabric.compat.mubble.MubbleMixinPlugin.preApply(MubbleMixinPlugin.java:71)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1341)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1177)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:308)
	... 25 more
	at net.minecraft.class_128.method_24305(class_128.java:425) [intermediary-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) [intermediary-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_261]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
Caused by: java.lang.IllegalArgumentException: Can't find Mixin class com/hugman/dawn/mod/mixin/ItemRendererMixin targetting net.minecraft.class_918
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.findMixin(InterceptingMixinPlugin.java:93) ~[【光影兼容】optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.preApply(InterceptingMixinPlugin.java:43) ~[【光影兼容】optifabric-1.9.2.jar:?]
	at me.modmuss50.optifabric.compat.mubble.MubbleMixinPlugin.preApply(MubbleMixinPlugin.java:71) ~[【光影兼容】optifabric-1.9.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.preApply(PluginHandle.java:158) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.preApply(MixinInfo.java:1341) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.preApply(MixinTargetContext.java:1177) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:308) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	... 25 more**

**Comment by italycalibur2019** [comment]
My Minecraft version: 1.16.5

**Comment by Hugman76** [comment]
We do not support issues concerning OptiFabric.
