### ISSUE TITLE
Bone meal lettuce crash

### ISSUE THREAD

**Issue by VoidLock92** [DawnTeamMC/Culinaire#13]
I get this crash when using bone meal on lettuce:

java.lang.IllegalArgumentException: Cannot get property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{culinaire:lettuce}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.github.olivermakescode.srch.SimpleHarvest.lambda$onInitialize$0(SimpleHarvest.java:29)
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
	at net.minecraft.class_636.handler$ccc000$interactBlock(class_636.java:2672)
	at net.minecraft.class_636.method_2896(class_636.java:308)
	at net.minecraft.class_310.method_1583(class_310.java:1646)
	at net.minecraft.class_310.method_1508(class_310.java:1900)
	at net.minecraft.class_310.method_1574(class_310.java:1728)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by YanisBft** [comment]
I cannot reproduce this issue, bone mealing lettuce seeds works fine. What other mods are you using?

**Comment by VoidLock92** [comment]
Hmm it seems it was SimpleHarvest causing the issue, its a mod to allow for right click harvesting of crops.

**Comment by Hugman76** [comment]
You should probably see this with SimpleHarvest's author(s) then... Cannot reproduce.
